config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurants#index'

  resources :restaurants, only: [:index, :new, :create, :show]

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  resources :restaurants, only: [:index, :new, :create, :show]

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :name, presence: :true
  validates :address, presence: :true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :restaurant, presence: :true

  validates :content, presence: :true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
      render :action => :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [ :new, :create ]

    def new
      @review = Review.new
    end

    def create
      @review = @restaurant.reviews.build(review_params)
      if @review.save
        redirect_to restaurant_path(@restaurant)
      else
        render :action => :new
      end
    end

    private

    def review_params
      params.require(:review).permit(:content, :rating)
    end

    def find_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= yield %>

</body>
</html>

app/views/restaurants/_formreview.html.erb
<%= form_for [@restaurant, @review] do |f| %>
<%= f.text_field :content %>
<%= f.select :rating, options_for_select(0..5) %>
<%= f.submit "add a review" %>
<% end %>

app/views/restaurants/index.html.erb
<h2>Restaurants list</h2>
<% @restaurants.each do |restaurant| %>
<h3><%= restaurant.name %></h3>
<p>Category: <%=restaurant.category%></p>
<p><i><%= restaurant.address %></i></p>
<p><%= link_to "details", restaurant_path(restaurant) %></p>
<% end %>
<p><%= link_to "add restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>
<%= form_for(@restaurant) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %>
<%= f.select :category, [['French','french'],['Italian','italian'],['Chinese','chinese'], ['Japanese', 'japanese'], ['Belgian', 'belgian']] %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>You picked</h1>
<h2><%= @restaurant.name %></h2>
<p>Category: <%=@restaurant.category%></p>
<p><i><%= @restaurant.address %></i></p>

<!-- ask for a new review -->

<%= render partial: "formreview" %>

<!-- show reviews -->
<% @restaurant.reviews.each do |review| %>
<p><%= review.content %></p>
<p><i><%= review.rating %></i></p>
<% end %>

<p><%= link_to "Back to list", restaurants_path %></p>